/* Main.c file generated by New Project wizard
*
* Created:   ju. oct. 12 2023
* Processor: PIC18F45K22
* Compiler:  MPLAB XC8
*/

#include <xc.h>
#include "config.h"
#define _XTAL_FREQ 8000000
#include <stdlib.h>

int detectEdge (int PORT_ant, int PORT_act, int pin, int edge)
{
    int mask = 1 << pin;

        if (edge == 1) 
        {
            if ((PORT_ant & mask) == 0 && (PORT_act & mask) != 0) return 1;
        }
        else
        {
            if ((PORT_ant & mask) != 0 && (PORT_act & mask) == 0) return 1;
        }

    return 0;
 }

void configPIC()
{
    ANSELA=0x00; // All pins as digital
    ANSELB=0x00;
    ANSELC=0x00;
    ANSELD=0x00;
    ANSELE=0x00;
    TRISA=0x0F; // 1111 to inp
    TRISB=0x00; //output
    TRISC=0x00; //output
    TRISD=0x00; //output
    TRISE=0x00; //output
    PORTA=0x00;
    PORTB=0x00;
    PORTC=0x00;
    PORTD=0x00;
    PORTE=0x00;
}


void main(void)
{
    int delay_refresh = 5;
    configPIC();
    srand(33);
    int ant_PORTC = PORTC;
    int d4,d3,d2,d1;


    int nums[10];

    nums[0] = 0b00111111;
    nums[1] = 0b00000110;
    nums[2] = 0b01011011;
    nums[3] = 0b01001111;
    nums[4] = 0b01100110;
    nums[5] = 0b01101101;
    nums[6] = 0b01111101;
    nums[7] = 0b00000111;
    nums[8] = 0b01111111;
    nums[9] = 0b01101111;

    PORTA = 0x0F; // tots els displays
    PORTD = nums[0] // a 0

    while (1) {
        if(detectEdge(ant_PORTC, PORTC, 7, 1) == 1) {
            int num1 = rand()%100
        }
        d1 = num1%10;
        d2 = num1/10;


    

        ant_PORTC = PORTC;

        PORTA = 1;
	    PORTD = num[d1];
	    __delay_ms(delay_refresh);
	    PORTA = 2;
	    PORTD = num[d1];
        __delay_ms(delay_refresh);
        PORTA = 4;
        PORTD = num[d1];
        __delay_ms(delay_refresh);
        PORTA = 8;
        PORTD = num[d1];
        __delay_ms(delay_refresh);
    }

}