/* Main.c file generated by New Project wizard
 *
 * Created:   ju. oct. 12 2023
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include "config.h"
#define _XTAL_FREQ 8000000
#include <time.h>
#include <stdlib.h>

int detectEdge (int PORT_ant, int PORT_act, int pin, int edge)
{
  int mask = 1 << pin;

    if (edge == 1) 
    {
        if ((PORT_ant & mask) == 0 && (PORT_act & mask) != 0) return 1;
    }
    else
    {
        if ((PORT_ant & mask) != 0 && (PORT_act & mask) == 0) return 1;
    }

  return 0;
}

void configPIC(){
   ANSELA=0x00; // All pins as digital
   ANSELB=0x00;
   ANSELC=0x00;
   ANSELD=0x00;
   ANSELE=0x00;
   TRISA=0x0F; // 1111 to inp
   TRISB=0x00; //output
   TRISC=0x00; //output
   TRISD=0x00; //output
   TRISE=0x00; //output
   PORTA=0x00;
   PORTB=0x00;
   PORTC=0x00;
   PORTD=0x00;
   PORTE=0x00;
}


void main(void)
 {
   configPIC();
   srand(time(NULL));
   int ant_PORTC = PORTC;
   while (1) {
      if(detectEdge(ant_PORTC, PORTC, 7, 1)) {
      
      }
      
      ant_PORTC = PORTC;
   }
   //__delay_ms(33)
   //__delay_us(33)
      
 }